### ISSUE TITLE
Consider using a task-dir layout

### ISSUE THREAD

**Issue by jchesterpivotal** [pivotal-cf/pcf-bosh-ci#1]
Currently the repo is broken into `tasks/` and `scripts/`. I think this is an antipattern, as it leads to bouncing up and down in large CI repos trying to follow logic.

The task-dir pattern is much easier to work with. You combine the task YAML and any logic into a single directory under `tasks/`. By convention the YAML is called `task.yml` and the entrypoint script is `run.sh,rb,whatever`.

For example, see [buildpacks-ci/tasks](https://github.com/cloudfoundry/buildpacks-ci/tree/master/tasks). See [`run-shellcheck`](https://github.com/cloudfoundry/buildpacks-ci/tree/master/tasks/run-shellcheck) for an example of having an entrypoint and supporting logic.

**Comment by wendorf** [comment]
@jchesterpivotal The scripts that correspond to `[my-task].yml` files are in the `tasks/` directory as well, e.g. `tasks/deploy-mysql.yml` and `tasks/deploy-mysql.sh`. I think this actually causes less bouncing since there are no subdirectories.

The `scripts/` directory is just for ancillary scripts, like `yaml2json` or setting environment variables for the bosh CLI. Nothing in that directory is called directly by Concourse.

**Comment by wendorf** [comment]
Hi @jchesterpivotal ,

I'm going to close this issue, but if you have additional thoughts about what would be a better structure, feel free to open a new one or reopen this one.
